# Generated by Django 4.0.5 on 2022-06-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.PositiveSmallIntegerField()),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'Madre'), (2, 'Padre'), (3, 'Hijo'), (4, 'Hija'), (5, 'Mascota')])),
                ('fecha_de_nacimiento', models.DateField()),
            ],
        ),
    ]
